### ISSUE TITLE
getCookie e setCookie duplicato

### ISSUE THREAD

**Issue by CremaLuca** [Slthy/touchy#1]
https://github.com/Slthy/touchyOnSvelteKit/blob/bcec7e017944320a006892295dfd89bfa9a24392/src/routes/register.svelte#L7

Sia su login che su register hai definito `getCookie` e `setCookie`, sei sicuro non esista una libreria che faccia già queste cose?
Se non esiste la libreria, non sarebbe meglio mettere i metodi dentro ad un file `utils` e chiamare le funzioni li dentro?

**Comment by Slthy** [comment]
Yep esiste una libreria ([https://github.com/pixelmund/svelte-kit-cookie-session](url)) per salvare I cookies e cifrarli ma:

> 1) mi sembra troppo overkill
> 2) restando in locale, non dovrebbero esserci problemi, tranne in casi di attacchi mirati al client
