### ISSUE TITLE
Hard-coded backend url

### ISSUE THREAD

**Issue by CremaLuca** [Slthy/touchy#2]
https://github.com/Slthy/touchyOnSvelteKit/blob/bcec7e017944320a006892295dfd89bfa9a24392/src/routes/register.svelte#L31

Usi ovunque `localhost:3600`, potresti estrarre la stringa `BACKEND_URL = 'localhost:3600'` ed usare quella come base per tutte le richieste che fa l'applicazione, altrimenti quando metterai live il sito e magari il backend cambierà dovrai fare un find e replace con il rischio di dimenticarti qualcosa.

**Comment by Slthy** [comment]
thx del suggerimento, avevo visto che lo avevi fatto in fantanuoto ma non lo avevo ancora implementato nel mio.

lol, è rimasto il vecchio commit con il titolo sbagliato
