### ISSUE TITLE
Hard coded cookie time

### ISSUE THREAD

**Issue by CremaLuca** [Slthy/touchy#3]
https://github.com/Slthy/touchyOnSvelteKit/blob/2576cf47399f4c7ab909140ed4843eae9bbebf54/src/lib/utils.js#L4-L7

Potresti voler cambiare il tempo di vita di un cookie dipendentemente dal suo contenuto o dalla sua utilità. Abituati a non hard-code parametri all'interno del codice ma a renderli come parametri con un valore di default.

In più i valori di default a meno che non siano scontati ricordati di metterli sempre all'inizio del file così quando vuoi cambiarli non devi andare a cercare dove sono.

```js
DEFAULT_COOKIE_DURATION = 86400000
 export function setCookie(cname, cvalue, duration = DEFAULT_COOKIE_DURATION) { 
   if (browser) { 
     const d = new Date(); 
     d.setTime(d.getTime() + duration); 
```

**Comment by CremaLuca** [comment]
Aggiornamenti @Slthy?

**Comment by Slthy** [comment]
Patchato nel refactoring aggiungendo variabili globali
